const currencyCodes = [
    { code: "AFN", name: "Afegane Afegão" },
    { code: "MGK", name: "Ariary Malgaxe" },
    { code: "PAB", name: "Balboa Panamenho" },
    { code: "THB", name: "Baht Tailandês" },
    { code: "ETB", name: "Birr Etíope" },
    { code: "VES", name: "Bolívar Venezuelano" },
    { code: "BOB", name: "Boliviano" },
    { code: "GHS", name: "Cedi Ganês" },
    { code: "NIO", name: "Córdoba Nicaraguense" },
    { code: "CRC", name: "Colón da Costa Rica" },
    { code: "CZK", name: "Coroa Checa" },
    { code: "DKK", name: "Coroa Dinamarquesa" },
    { code: "FOK", name: "Coroa Faroense" },
    { code: "ISK", name: "Coroa Islandesa" },
    { code: "NOK", name: "Coroa Norueguesa" },
    { code: "SEK", name: "Coroa Sueca" },
    { code: "GMD", name: "Dalasi Gambiano" },
    { code: "DZD", name: "Dinar Argelino" },
    { code: "IQD", name: "Dinar Iraquiano" },
    { code: "JOD", name: "Dinar Jordaniano" },
    { code: "KWD", name: "Dinar Kuwaitiano" },
    { code: "LYD", name: "Dinar Líbio" },
    { code: "MKD", name: "Dinar Macedônio" },
    { code: "RSD", name: "Dinar Sérvio" },
    { code: "TND", name: "Dinar Tunisiano" },
    { code: "AED", name: "Dirham dos Emirados Árabes Unidos" },
    { code: "MAD", name: "Dirham Marroquino" },
    { code: "STN", name: "Dobra de São Tomé e Príncipe" },
    { code: "USD", name: "Dólar Americano" },
    { code: "AUD", name: "Dólar Australiano" },
    { code: "CAD", name: "Dólar Canadense" },
    { code: "GYD", name: "Dólar da Guiana" },
    { code: "BSD", name: "Dólar das Bahamas" },
    { code: "BMD", name: "Dólar das Bermudas" },
    { code: "KYD", name: "Dólar das Ilhas Cayman" },
    { code: "SBD", name: "Dólar das Ilhas Salomão" },
    { code: "BBD", name: "Dólar de Barbados" },
    { code: "FJD", name: "Dólar de Fiji" },
    { code: "HKD", name: "Dólar de Hong Kong" },
    { code: "KID", name: "Dólar de Kiribati" },
    { code: "SGD", name: "Dólar de Singapura" },
    { code: "TTD", name: "Dólar de Trinidad e Tobago" },
    { code: "TVD", name: "Dólar de Tuvalu" },
    { code: "BND", name: "Dólar do Brunei" },
    { code: "XCD", name: "Dólar do Caribe Oriental" },
    { code: "JMD", name: "Dólar Jamaicano" },
    { code: "LRD", name: "Dólar Liberiano" },
    { code: "NAD", name: "Dólar Namibiano" },
    { code: "NZD", name: "Dólar Neozelandês" },
    { code: "SRD", name: "Dólar Surinamês" },
    { code: "ZWL", name: "Dólar Zimbabuano" },
    { code: "VND", name: "Dong Vietnamita" },
    { code: "AMD", name: "Dram Armênio" },
    { code: "CVE", name: "Escudo Cabo-Verdiano" },
    { code: "EUR", name: "Euro" },
    { code: "AWG", name: "Florim Arubano" },
    { code: "ANG", name: "Florim das Antilhas Holandesas" },
    { code: "HUF", name: "Forint Húngaro" },
    { code: "BIF", name: "Franco Burundiano" },
    { code: "XAF", name: "Franco CFA Central Africano" },
    { code: "XOF", name: "Franco CFA da África Ocidental" },
    { code: "XPF", name: "Franco CFP" },
    { code: "KMF", name: "Franco Comorense" },
    { code: "CDF", name: "Franco Congolês" },
    { code: "DJF", name: "Franco do Djibuti" },
    { code: "GNF", name: "Franco Guineano" },
    { code: "RWF", name: "Franco Ruandês" },
    { code: "CHF", name: "Franco Suíço" },
    { code: "HTG", name: "Gourde Haitiano" },
    { code: "PYG", name: "Guarani Paraguaio" },
    { code: "UAH", name: "Hryvnia Ucraniana" },
    { code: "JPY", name: "Iene Japonês" },
    { code: "PGK", name: "Kina Papua-Nova Guineana" },
    { code: "LAK", name: "Kip Laociano" },
    { code: "HRK", name: "Kuna Croata" },
    { code: "AOA", name: "Kwanza Angolano" },
    { code: "MWK", name: "Kwacha Malauiano" },
    { code: "ZMW", name: "Kwacha Zambiano" },
    { code: "GEL", name: "Lari Georgiano" },
    { code: "ALL", name: "Lek Albanês" },
    { code: "HNL", name: "Lempira Hondurenha" },
    { code: "SLL", name: "Leone de Serra Leoa" },
    { code: "SSP", name: "Libra Sul-Sudanesa" },
    { code: "SYP", name: "Libra Síria" },
    { code: "SZL", name: "Lilangeni Suazi" },
    { code: "TRY", name: "Lira Turca" },
    { code: "LSL", name: "Loti do Lesoto" },
    { code: "MDL", name: "Leu Moldávio" },
    { code: "MMK", name: "Kyat Birmanês" },
    { code: "AZN", name: "Manat Azeri" },
    { code: "TMT", name: "Manat Turcomeno" },
    { code: "MZN", name: "Metical Moçambicano" },
    { code: "NGN", name: "Naira Nigeriana" },
    { code: "TWD", name: "Novo Dólar Taiwanês" },
    { code: "MRU", name: "Ouguiya Mauritana" },
    { code: "MOP", name: "Pataca de Macau" },
    { code: "TOP", name: "Paʻanga Tonga" },
    { code: "PHP", name: "Peso Filipino" },
    { code: "MXN", name: "Peso Mexicano" },
    { code: "UYU", name: "Peso Uruguaio" },
    { code: "ZAR", name: "Rand Sul-Africano" },
    { code: "QAR", name: "Rial Catarense" },
    { code: "BRL", name: "Real Brasileiro" },
    { code: "MYR", name: "Ringgit Malaio" },
    { code: "OMR", name: "Rial Omanense" },
    { code: "YER", name: "Rial Iemenita" },
    { code: "SAR", name: "Riyal Saudita" },
    { code: "NPR", name: "Rúpia Nepalesa" },
    { code: "PKR", name: "Rúpia Paquistanesa" },
    { code: "SCR", name: "Rúpia de Seychelles" },
    { code: "MUR", name: "Rúpia Mauriciana" },
    { code: "MVR", name: "Rufiyaa Maldiva" },
    { code: "PEN", name: "Sol Peruano" },
    { code: "UZS", name: "Som Uzbeque" },
    { code: "TJS", name: "Somoni do Tajiquistão" },
    { code: "WST", name: "Tala Samoano" },
    { code: "MNT", name: "Tögrög Mongol" },
    { code: "VUV", name: "Vatu Vanuatuense" },
    { code: "SOS", name: "Xelim Somalí" },
    { code: "TZS", name: "Xelim Tanzaniano" },
    { code: "UGX", name: "Xelim Ugandês" },
    { code: "PLN", name: "Złoty Polonês" },


  ];

const CurrencySelect = ({ selectedCurrency, handleCurrency }) => {
  const countryCode = selectedCurrency.substring(0, 2);
  return (
    <div className="currency-select">
      <img src={`https://flagsapi.com/${countryCode}/flat/64.png`} alt="Flag" />
      <select
        className="currency-dropdown"
        value={selectedCurrency}
        onChange={handleCurrency}
      >
        {currencyCodes.map((currency) => (
          <option key={currency.code} value={currency.code}>
            {currency.name}
          </option>
        ))}
      </select>
    </div>
  );
};

export default CurrencySelect;
